Note that the script only works on python2
Spend about 30 mins debugging this on my dads machine only to realize he was trying to run it through python3 and getting:

```
bret-mbr:wtpa2-python bret$ python3 wtpa2.py pack samples.bin /Volumes/WTPA2/aif
Traceback (most recent call last):
  File "wtpa2.py", line 210, in <module>
    wtpa.pack(args.outfile, args.infiles)
  File "wtpa2.py", line 25, in pack
    self.header[0:3] = "WTPA"
TypeError: can assign only bytes, buffers, or iterables of ints in range(0, 256)
```

Script worked great once it was used with python2.